spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ticket
    username: root
    password: lonnie414?
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true # hibernate ?? ???